//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.08 at 10:30:17 AM CEST 
//


package org.liris.mTrace.jaxb.base;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.liris.mTrace.jaxb.base package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Label_QNAME = new QName("", "label");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.liris.mTrace.jaxb.base
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Method }
     * 
     */
    public Method createMethod() {
        return new Method();
    }

    /**
     * Create an instance of {@link Trace }
     * 
     */
    public Trace createTrace() {
        return new Trace();
    }

    /**
     * Create an instance of {@link ObselType }
     * 
     */
    public ObselType createObselType() {
        return new ObselType();
    }

    /**
     * Create an instance of {@link ObselTypeFigure }
     * 
     */
    public ObselTypeFigure createObselTypeFigure() {
        return new ObselTypeFigure();
    }

    /**
     * Create an instance of {@link Traces }
     * 
     */
    public Traces createTraces() {
        return new Traces();
    }

    /**
     * Create an instance of {@link Model }
     * 
     */
    public Model createModel() {
        return new Model();
    }

    /**
     * Create an instance of {@link Obsel }
     * 
     */
    public Obsel createObsel() {
        return new Obsel();
    }

    /**
     * Create an instance of {@link Description }
     * 
     */
    public Description createDescription() {
        return new Description();
    }

    /**
     * Create an instance of {@link Base }
     * 
     */
    public Base createBase() {
        return new Base();
    }

    /**
     * Create an instance of {@link TraceModelFigure }
     * 
     */
    public TraceModelFigure createTraceModelFigure() {
        return new TraceModelFigure();
    }

    /**
     * Create an instance of {@link TraceModelFigures }
     * 
     */
    public TraceModelFigures createTraceModelFigures() {
        return new TraceModelFigures();
    }

    /**
     * Create an instance of {@link ObselTypes }
     * 
     */
    public ObselTypes createObselTypes() {
        return new ObselTypes();
    }

    /**
     * Create an instance of {@link SuperMethod }
     * 
     */
    public SuperMethod createSuperMethod() {
        return new SuperMethod();
    }

    /**
     * Create an instance of {@link Param }
     * 
     */
    public Param createParam() {
        return new Param();
    }

    /**
     * Create an instance of {@link Obsels }
     * 
     */
    public Obsels createObsels() {
        return new Obsels();
    }

    /**
     * Create an instance of {@link Params }
     * 
     */
    public Params createParams() {
        return new Params();
    }

    /**
     * Create an instance of {@link Lines.Line }
     * 
     */
    public Lines.Line createLinesLine() {
        return new Lines.Line();
    }

    /**
     * Create an instance of {@link Methods }
     * 
     */
    public Methods createMethods() {
        return new Methods();
    }

    /**
     * Create an instance of {@link Lines }
     * 
     */
    public Lines createLines() {
        return new Lines();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "label")
    public JAXBElement<String> createLabel(String value) {
        return new JAXBElement<String>(_Label_QNAME, String.class, null, value);
    }

}
